[Interface]
PrivateKey = <wg-client-private-key>
Address = <client-ip-address/cidr>
DNS = <pihole-lan-ip-address>

[Peer]
PublicKey = <wg-server-public-key>
Endpoint = <home-network-public-ip>:<wg-listening-port>
AllowedIPs = <home-network-address-space>, <wg-network-address-space>
PersistentKeepalive = 25 # Optional