[Interface]
PrivateKey = <wg-server-private-key>
ListenPort = <wg-listening-port> # E.g. 51000
Address = <wg-tunnel-ip-address/cidr>

[Peer]
PublicKey = <wg-client-public-key>
AllowedIPs = <wg-client-ip-address/32>

[Peer]
PublicKey = <wg-client-public-key>
AllowedIPs = <wg-client-ip-address/32>